# Pre-commit hooks for Terraform/Terragrunt project

repos:
  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      # Auto-fix: Format Terraform files
      - id: terraform_fmt
        name: Terraform fmt
        description: Auto-format Terraform files to canonical format
        
      # Check: Validate Terraform syntax
      - id: terraform_validate
        name: Terraform validate
        description: Validate Terraform configuration files
        args:
          - --hook-config=--retry-once-with-cleanup=true
        
      # Optional: Generate documentation (disabled by default - enable if needed)
      # - id: terraform_docs
      #   name: Terraform docs
      #   description: Generate README for modules
      #   args:
      #     - --hook-config=--path-to-file=README.md
      #     - --hook-config=--add-to-existing-file=true
      
      # Security: Scan for security issues (WARNING level only)
      - id: terraform_tfsec
        name: Terraform tfsec
        description: Security scanning with tfsec
        args:
          - --args=--minimum-severity=HIGH  # Only show HIGH and CRITICAL issues
          - --args=--exclude-downloaded-modules  # Skip third-party modules

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Auto-fix: Remove trailing whitespace
      - id: trailing-whitespace
        name: Trim trailing whitespace
        
      # Auto-fix: Ensure files end with newline
      - id: end-of-file-fixer
        name: Fix end of files
        
      # Check: Prevent committing large files (>500KB)
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=500']
        
      # Check: Prevent merge conflict markers
      - id: check-merge-conflict
        name: Check for merge conflicts
        
      # Check: Ensure JSON files are valid
      - id: check-json
        name: Check JSON syntax
        
      # Check: Ensure YAML files are valid
      - id: check-yaml
        name: Check YAML syntax
        args: ['--allow-multiple-documents']

  # Git checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Check: Prevent committing to main/master directly
      - id: no-commit-to-branch
        name: Don't commit to main
        args: ['--branch=main', '--branch=master']
        stages: [commit]

# Configuration
fail_fast: false  # Run all hooks even if one fails
default_stages: [commit]  # Only run on commit, not push
